runtime: python311
entrypoint: python main.py
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 5
env_variables:
  GOOGLE_CLOUD_PROJECT: project-drishti-466708
  GOOGLE_CLOUD_REGION: us-central1
  # Other config vars (API keys, bucket names, etc.)
